version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ./config/mysql.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql-db:/var/lib/mysql
# Volumes to persist data
volumes:
  mysql-db: